---
title: "Práctica 01"
author: "Peredo Leonel"
output: pdf_document
---
# Correlación

1. El conjunto de datos bdims del paquete openintro que se habilita en el workspace del R con los comandos
library(openintro)
data(bdims, package = ‘‘openintro’’)
El archivo consiste en medidas del di´ametro y circunferencia de distintas partes del cuerpo (21 variables),
as´ı como edad, peso, altura y g´enero de 507 personas f´ısicamente activas. Para m´as detalle, tipear
help(bdims, package = ‘‘openintro’’)
a) Calcular las correlaciones muestrales entre las 21 variables que miden el di´ametro o circunferencia de
las distintas partes del cuerpo. ¿Cu´antas correlaciones debe calcular? ¿Cu´al ser´ıa la mejor manera de
exhibir esta informaci´on? ¿Est´an positiva o negativamente correlacionadas estas variables?
b) Encontrar las dos variables con mayor correlaci´on entre s´ı. Realizar un scatter plot. ¿Le parece que este
n´umero resume adecuadamente el v´ınculo entre ambas variables?
c) Repetir con las de menor correlaci´on.
d) Hacer un scatter plot de peso en el eje y y altura en el eje x y calcular la correlaci´on muestral o de
Pearson. ¿Le parece que este n´umero resume adecuadamente el v´ınculo entre ambas variables?
e) Hacer scatter plots de la variable bia di, que es la distancia biacromial (informalmente, la distancia
emtre los hombros) con las siguientes cuatro variables y calcular las correlaciones de a pares para ambas.
Observar c´omo se comportan los scatterplots para distintos valores de la correlaci´on.
age, la edad
bii di, el ancho de la pelvis
che de, la profundidad del pecho
wri di, la circunferencia de la mu˜neca